#!/usr/bin/env bash

sudo apt install -y \
  git               \
  neovim            \
  ranger            \
  make              \
  tmux              \
  zsh               \
  xsel

cd ./common-dotfiles

if [ "$SHELL" != "/bin/zsh" ]; then
  chsh -s /bin/zsh
  echo -e "Shell changed to Zsh.\nPlease log out and log back.\nThen start script again."
  exit
fi

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all

make clean
make nvim
make symlink

sudo cp -rf ./configs/tmux           /root/.tmux
sudo cp -rf ./configs/config/ranger/ /root/.config/
sudo cp -rf ./configs/config/nvim/   /root/.config/
sudo cp -rf ./configs/config/zshrc   /root/.zshrc

sudo ln -s /root/.tmux/tmux.conf     /root/.tmux.conf


# TODO: Make capslock - right ctrl.
# TODO: Prepare dotfiles and put them to /etc/skel. Script that will change usernames is required.

echo "Now you can re-login into the shell."
